### ISSUE TITLE
last row not adjust

### ISSUE THREAD

**Issue by jksenthilraja** [xremix/xGallerify#21]
Last row not adjust in my gallery, single item show in my last row of gallery. how to solve this problem.

**Comment by xremix** [comment]
@jksenthilraja have you tried both options for for the parameter `lastRow` like

``` JS
$('.photos').gallerify({
    mode:'default',
    lastRow:'adjust',
});
```

and 

``` JS
$('.photos').gallerify({
    mode:'default',
    lastRow:'fullwidth',
});
```

like described in the docs? Is there an option that fits your needs?

The Gallery is working based on a maximum number of items in a row - if you don't have a fitting number of images the last row might have only one image, but will be centered.

In theory the gallery could use one image of the second last row to not have only one image in the last row, but that wouldn't solve the issue as 2 images on a 4k screen would still be too less and would be centered in the middle.

If you have a recommendation or idea for improvement let me know.

**Comment by JohnnyTheTank** [comment]
There should be this option: `lastRow: 'none'` which removes the last uncomplete row

**Comment by xremix** [comment]
That sounds like a good alternate solution for people that don't care about showing all images.

I can push a fix this afternoon.

BTW: other galleries struggle with the same issue and don't have satisfying solutions as well - at least I didn't find one.

**Comment by xremix** [comment]
A big downside would be that this is going to be hidden on mobile (or eventually smaller screens) and this would also hide panorama images that have a with that would fill the screen - but there could be a solution for that.

**Comment by jksenthilraja** [comment]
Thank you guys!

**Comment by xremix** [comment]
@jksenthilraja I'm working on this, but as long as I don't have a final version / have the best approach you might want to check out #22 wich has the beta code of my changes.

**Comment by xremix** [comment]
I did some testing and my changes seem to work fine for a first update.
