### ISSUE TITLE
lastRow set to fullwidth makes last row wider than other rows

### ISSUE THREAD

**Issue by DrifterAtSea** [xremix/xGallerify#29]
I ran your codepen demo and set lastRow to fullscreen. The width of the last row ends up being wider than all the other rows. This doesn't look good. All rows should be the same width.

**Comment by xremix** [comment]
Thanks for letting me know @JohannBlake , it seems a little but creeped in here, as this was not the case before. I'll take a look at this.

**Comment by xremix** [comment]
@JohannBlake I fixed this bug, was little code but hard to figure out. Let me know if you have issues with this.
I'm going to deploy this to bower and NPM now.

And if you like my support I'd be happy if you leave a star 👍

**Comment by xremix** [comment]
Btw. I'd recommend using the following CDN: https://cdn.rawgit.com/xremix/xGallerify/v0.1.5/dist/jquery.xgallerify.min.js
As jsdelivr seems to have issues as they didn't fetched the latest version when I tried.

**Comment by DrifterAtSea** [comment]
What do you mean by "didn't fetch the latest version"? Is there an issue with the version in Github?

**Comment by xremix** [comment]
No that will work, just in case you want a CDN
